diario/urls.py
from django.contrib.auth import views as auth_views
from django.contrib import admin
from django.urls import path
from django.urls import path 
from . import views 


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('registro/', views.registro, name='registro'),
    path('calendario/', views.calendario, name='calendario'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('calendario/', views.calendario, name='calendario'),
    path('evento/<int:evento_id>/', views.detalhe_evento, name='detalhe_evento'),
    path('diario/', views.diario, name="diario"),
    path('salvar_nome_diario/', views.salvar_nome_diario, name="salvar_nome_diario"),
    path('salvar_pagina/', views.salvar_pagina, name='salvar_pagina'),
    path('buscar_todas_paginas/', views.buscar_todas_paginas, name='buscar_todas_paginas'),
    path('editar-diario/<int:diario_id>/', views.editar_diario, name='editar_diario'),
    path('save_page_count/', views.save_page_count, name='save_page_count'),
    path('create_event/', views.create_event, name='create_event'),
    path('get_events/', views.get_events, name='get_events'),
    path('get_recommendations/', views.get_recommendations, name='get_recommendations'),
    path('salvar_anotacao/', views.salvar_anotacao, name="salvar_anotacao"),
    path('buscar_anotacoes/', views.buscar_anotacoes, name="buscar_anotacoes"),
    path('excluir_anotacao/<int:anotacao_id>/', views.excluir_anotacao, name='excluir_anotacao'),
    path('buscar_por_conteudo/', views.buscar_por_conteudo, name='buscar_por_conteudo'),
    path('salvar_humor/', views.salvar_humor, name='salvar_humor'),
    path('get_today_page_count/', views.get_today_page_count, name='get_today_page_count'),
    path('acompanhamento/', views.list_acompanhamento_semanal, name='acompanhamento'),
    path('analyze_sentiment/', views.analyze_sentiment, name='analyze_sentiment'),
    path('analyze_mood_change/', views.analyze_mood_change, name='analyze_mood_change'),
    path('consultar_eventos/', views.consultar_eventos, name='consultar_eventos'),
    path('acompanhamento_semanal_view/', views.acompanhamento_semanal_view, name='acompanhamento_semanal_view'),
    path('acompanhamento_semanal/', views.acompanhamento_semanal_view, name='acompanhamento_semanal'),
    path('delete-acompanhamento/<int:id>/', views.delete_acompanhamento, name='delete_acompanhamento'),
    path('add_note/<int:event_id>/', views.add_note, name='add_note'),
    path('delete_note/<int:note_id>/', views.delete_note, name='delete_note'),
    path('download_pdf_view_criar/', views.download_pdf_view_criar, name='download_pdf_view_criar'),
    path('download_word/', views.download_word_view, name='download_word'),
    path('acompanhamentos/download/<int:acompanhamento_id>/', views.download_pdf_view, name='download_pdf_view'),
    path('acompanhamento/<int:id>/', views.view_acompanhamento, name='view_acompanhamento'),
]

diario/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.conf import settings

class Diario(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    nome = models.CharField(max_length=100)
    data_criacao = models.DateTimeField(default=timezone.now)
    

class Pagina(models.Model):
    diario = models.ForeignKey(Diario, related_name='paginas', on_delete=models.CASCADE)
    numero_pagina = models.IntegerField()
    conteudo = models.TextField(blank=True)

    class Meta:
        unique_together = ['diario', 'numero_pagina']

    def __str__(self):
        return f"Pagina {self.numero_pagina} do {self.diario.nome}"

class Evento(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE) 
    titulo = models.CharField(max_length=200)
    descricao = models.TextField()
    data_inicio = models.DateTimeField()
    data_fim = models.DateTimeField()

    def __str__(self):
        return self.titulo

class Nota(models.Model):
    evento = models.ForeignKey(Evento, related_name='notas', on_delete=models.CASCADE)
    texto = models.TextField()
    criado_em = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.texto[:50]  

class PageCount(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)
    count = models.IntegerField()
    date = models.DateField()
    is_saved = models.BooleanField(default=False)

    
class Anotacao(models.Model):
    usuario = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='anotacoes')
    texto = models.TextField()
    data_criacao = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Anotação de {self.usuario.username} em {self.data_criacao.strftime('%d/%m/%Y %H:%M:%S')}"
    
class MoodLog(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateField()
    mood = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.user}'s mood on {self.date}: {self.mood}"

class AcompanhamentoSemanal(models.Model):
    nome = models.CharField(max_length=100)
    data = models.DateField()
    numero_sessao = models.IntegerField()
    avaliacao_humor = models.CharField(max_length=50)
    mudancas_humor = models.TextField()
    eventos_semana = models.TextField()
    sintomas = models.JSONField()
    estrategias_coping = models.JSONField()
    observacoes_terapeuta = models.TextField()
    objetivos_proxima_semana = models.TextField()

    def __str__(self):
        return self.nome

diario/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignUpForm(UserCreationForm):
    email = forms.EmailField(max_length=254, help_text='Requerido. Informe um endereço de email válido.')

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2', )

class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

diario/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib import messages
from django.views.decorators.http import require_POST
from django.shortcuts import redirect, get_object_or_404
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
import whisper
from django.core.files.base import ContentFile
from django.http import HttpResponse
import os
import re
from datetime import datetime
from babel.dates import format_date
from django.db.models.functions import TruncDate
from collections import OrderedDict
from itertools import groupby
import itertools
import google.generativeai as genai
import textwrap
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from .models import Diario, Pagina
from django.contrib.auth import authenticate, login, logout
from .forms import SignUpForm, LoginForm
from django.contrib.auth.models import User
from django.utils import timezone
import pytz
from django.utils.timezone import localtime, activate
from django.utils.timezone import now
from .models import MoodLog
from .models import Evento, Nota
from .models import PageCount
import datetime
from django.shortcuts import redirect
from django.utils.dateparse import parse_datetime
from django.core.serializers import serialize
from django.utils.timezone import localtime
import json
from django.views.decorators.http import require_http_methods
from .models import Anotacao
from docx import Document
from docx.shared import Pt
from docx.enum.text import WD_PARAGRAPH_ALIGNMENT
from docx.oxml.ns import qn
from docx.oxml import OxmlElement
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib.units import inch
from datetime import date, timedelta
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak
from reportlab.lib.enums import TA_CENTER
from .models import AcompanhamentoSemanal, MoodLog
from django.db.models import Q
from .models import AcompanhamentoSemanal
from datetime import date
from datetime import date, timedelta
from django.db.models import Count


def to_markdown(text):
    text = text.replace('•', '  *')
    return textwrap.indent(text, '> ', predicate=lambda _: True)

def home(request):
    if request.user.is_authenticated:
        return redirect('diario')  
    else:
        return redirect('login') 

def registro(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('diario') 
    else:
        form = SignUpForm()
    return render(request, 'registro.html', {'form': form})

def login_view(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('diario') 
        else:
            return render(request, 'login.html', {'form': form, 'error': 'Usuário ou senha inválidos'})
    else:
        form = LoginForm()
    return render(request, 'login.html', {'form': form})

def logout_view(request):
    logout(request)
    return redirect('login')  

@login_required
def calendario(request):
    activate(pytz.timezone('America/Sao_Paulo'))

    eventos = Evento.objects.filter(user=request.user, data_inicio__gte=now()).order_by('data_inicio')

    eventos_ajustados = [
        {
            'id': evento.id,
            'titulo': evento.titulo,
            'data_inicio': localtime(evento.data_inicio).strftime('%Hh%M'),  
            'data_fim': localtime(evento.data_fim).strftime('%Hh%M'),       
        } for evento in eventos
    ]

    proximos_eventos = eventos_ajustados[:5]

    return render(request, 'calendario.html', {
        'eventos': eventos_ajustados,
        'proximos_eventos': proximos_eventos
    })

@login_required
def detalhe_evento(request, evento_id):
    evento = get_object_or_404(Evento, pk=evento_id)
    return render(request, 'calendario.html', {'evento': evento})

@login_required
def diario(request):
    date_today = timezone.now().date()
    diario = Diario.objects.filter(user=request.user).first() 
    already_submitted = MoodLog.objects.filter(user=request.user, date=date_today).exists()
    context = {
        'diary_name': diario.nome if diario else None,
        'diarios': Diario.objects.filter(user=request.user).order_by('-data_criacao'),
        'already_submitted': already_submitted,
        'diario': diario  
    }

    return render(request, 'diario.html', context)

@login_required
def salvar_nome_diario(request):
    if request.method == "POST":
        nome_diario = request.POST.get('diary_name')
        diario, created = Diario.objects.get_or_create(user=request.user)
        diario.nome = nome_diario
        diario.save()

        return redirect('diario')
    else:
        
        return redirect('diario')
    

@login_required
@csrf_exempt 
def salvar_pagina(request):
    if request.method == 'POST':
        numero_pagina = request.POST.get('numero_pagina')
        conteudo = request.POST.get('conteudo')
        diario, _ = Diario.objects.get_or_create(user=request.user)  

        pagina, created = Pagina.objects.update_or_create(
            diario=diario,
            numero_pagina=numero_pagina,
            defaults={'conteudo': conteudo},
        )

        return JsonResponse({'status': 'sucesso'})
    else:
        return JsonResponse({'status': 'falha'}, status=400)
    
@login_required
def buscar_todas_paginas(request):
    try:
        diario = Diario.objects.get(user=request.user)
        paginas = diario.paginas.all().order_by('numero_pagina')
        dados_paginas = [{'numero_pagina': p.numero_pagina, 'conteudo': p.conteudo} for p in paginas]
        return JsonResponse({'status': 'sucesso', 'paginas': dados_paginas})
    except Diario.DoesNotExist:
        return JsonResponse({'status': 'erro', 'mensagem': 'Diário não encontrado'}, status=404)

@login_required
def editar_diario(request, diario_id):
    diario = get_object_or_404(Diario, id=diario_id, user=request.user)  
    if request.method == 'POST':
        diario.nome = request.POST.get('nome_diario')
        diario.save()
        return redirect('diario')  
    return render(request, 'editar_diario.html', {'diario': diario})

@login_required
def save_page_count(request):
    if request.method == 'POST':
        page_count = int(request.POST.get('page_count'))
        today = datetime.date.today()
        user = request.user

        existing_count = PageCount.objects.filter(user=user, date=today).first()
        if existing_count:
            existing_count.count = page_count
            existing_count.is_saved = True
            existing_count.save()
        else:
            PageCount.objects.create(user=user, count=page_count, date=today, is_saved=True)
        
        return JsonResponse({'status': 'success'})
    else:
        return JsonResponse({'status': 'error', 'message': 'Invalid request'}, status=400)

@login_required
def get_today_page_count(request):
    today_count = PageCount.objects.filter(user=request.user, date=datetime.date.today()).first()
    if today_count:
        return JsonResponse({'status': 'success', 'count': today_count.count})
    else:
        return JsonResponse({'status': 'error', 'message': 'No data found'}, status=404)

@require_POST
@login_required
def create_event(request):
    titulo = request.POST.get('titulo')
    descricao = request.POST.get('descricao')
    data_inicio = request.POST.get('data_inicio')
    data_fim = request.POST.get('data_fim')
    
    sao_paulo = pytz.timezone('America/Sao_Paulo')

    data_inicio = parse_datetime(data_inicio)
    if data_inicio:
        data_inicio = sao_paulo.localize(data_inicio)

    data_fim = parse_datetime(data_fim)
    if data_fim:
        data_fim = sao_paulo.localize(data_fim)
    
    Evento.objects.create(
        user=request.user,
        titulo=titulo,
        descricao=descricao,
        data_inicio=data_inicio,
        data_fim=data_fim
    )
    return redirect('calendario')


@login_required
def get_events(request):
    activate(pytz.timezone('America/Sao_Paulo'))

    eventos = Evento.objects.filter(user=request.user)

    eventos_data = []
    for evento in eventos:
        evento_dict = {
            'id': evento.id, 
            'title': evento.titulo,
            'start': localtime(evento.data_inicio).isoformat(),
            'end': localtime(evento.data_fim).isoformat(),
            'notas': list(evento.notas.all().values('id', 'texto', 'criado_em'))
        }
        eventos_data.append(evento_dict)

    return JsonResponse({'eventos': eventos_data})

api_key = 'AIzaSyASEelCOGxux50q-JQIIEoc9fWhxl-0mLE'
genai.configure(api_key=api_key)

@csrf_exempt
@require_http_methods(["POST"])
def get_recommendations(request):
    try:
        if not request.body:
            return JsonResponse({'error': 'No data provided'}, status=400)

        data = json.loads(request.body)
        
        user_prompt = data.get('prompt')
        if not user_prompt:
            return JsonResponse({'error': 'Prompt not provided'}, status=400)

        full_prompt = (
            "Você é um ajudante e deve ser curto e direto, recomende filmes, séries e livros e como eles podem ajudar com o problema"
            f"para ajudarem a pessoa com o seguinte problema: {user_prompt}"
        )

        model = genai.GenerativeModel('gemini-pro')

diario/views/auth_views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import AuthenticationForm
from django.contrib import messages

def custom_login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('login') 
            else:
                messages.error(request, "Nome de usuário ou senha inválidos.")
        else:
            messages.error(request, "Nome de usuário ou senha inválidos.")
    else:
        form = AuthenticationForm()
    return render(request, 'templates/login.html', {'form': form})

diario/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">

<body>
    {% block head_extra %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}" media="screen" />
    <title>{% block title %}Meu Diário{% endblock %}</title>
    {% endblock %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <a class="navbar-brand" href="{% url 'diario' %}">
            MEU DIÁRIO <i class="fa-solid fa-book"></i>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="#"><span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'acompanhamento' %}">Relatório</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'calendario' %}">Calendário</a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="#">{{ user.username }}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}">Login</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>
    {% if user.is_authenticated %}
    {% if diario and not already_submitted %}
    <div class="modal-overlay">
        <div class="mood-selector">
            <p>Como você está se sentindo hoje?</p>
            <form action="{% url 'salvar_humor' %}" method="post">
                {% csrf_token %}
                <button type="submit" name="mood" value="feliz">😊 Feliz</button>
                <button type="submit" name="mood" value="triste">😢 Triste</button>
                <button type="submit" name="mood" value="irritado">😠 Irritado</button>
                <button type="submit" name="mood" value="ansioso">😟 Ansioso</button>
                <button type="submit" name="mood" value="entusiasmado">🤩 Entusiasmado</button>
                <button type="submit" name="mood" value="cansado">😴 Cansado</button>
                <button type="submit" name="mood" value="estressado">😖 Estressado</button>
                <button type="submit" name="mood" value="indiferente">😐 Indiferente</button>
                <button type="submit" name="mood" value="esperancoso">🙏 Esperançoso</button>
                <button type="submit" name="mood" value="inspirado">🌟 Inspirado</button>
            </form>
        </div>
    </div>
    {% endif %}
    {% endif %}



    {% block content %}



    {% endblock %}

    {% block scripts %}{% endblock %}
</body>

diario/templates/relatorio.html
{% extends "base.html" %}
{% load static %}

{% block head_extra %}
<meta charset="UTF-8">
<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}" media="screen" />
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="{% static 'css/relatorio/relatorio.css' %}" media="screen" />
<title>Acompanhamento Semanal</title>
{% endblock %}

{% block content %}
<div class="container-relatorio">
    <h4 class="h4-relatorio">Formulário de Acompanhamento Semanal</h4>
</div>
<div class="folha-container-relatorio">

    <form method="post" action="{% url 'acompanhamento_semanal' %}" id="form-acompanhamento">
        {% csrf_token %}
        <div class="form-acompanhamento-relatorio">
            <div class="form-group">
                <label for="nome">Nome:</label>
                <input type="text" class="form-control" id="nome" name="nome" value="{{ nome }}" readonly>
            </div>
            <div class="form-group">
                <label for="data">Data:</label>
                <input type="date" class="form-control" id="data" name="data" value="{{ data }}" readonly>
            </div>
            <div class="form-group">
                <label for="numero_sessao">Número da Sessão:</label>
                <input type="number" class="form-control" id="numero_sessao" name="numero_sessao"
                    value="{{ numero_sessao }}" readonly>
            </div>
        </div>
        <div class="form-group">
            <label for="sintomas">Sintomas:</label>
            <textarea class="form-control" id="sintomas" name="sintomas"></textarea>
        </div>
        <div class="form-group">
            <label for="estrategias_coping">Estratégias de Coping:</label>
            <textarea class="form-control" id="estrategias_coping" name="estrategias_coping"></textarea>
        </div>
        <div class="form-group">
            <label for="objetivos_proxima_semana">Objetivos para a Próxima Semana:</label>
            <textarea class="form-control" id="objetivos_proxima_semana" name="objetivos_proxima_semana"></textarea>
        </div>



        <input type="hidden" id="id_avaliacao_humor" name="avaliacao_humor">
        <input type="hidden" id="id_mudancas_humor" name="mudancas_humor">
        <input type="hidden" id="id_eventos_semana" name="eventos_semana">
        <div class="container-grafico">
            <div id="avaliacao-humor" class="output-div"></div>
            <div class="relatorio-grafico">
                <canvas id="moodChart" width="400" height="400"></canvas>
            </div>
        </div>
        <div id="mudancas-humor" class="output-div"></div>
        <div id="eventos-semana" class="output-div"></div>
        <div class="form-group">
            <label for="observacoes_terapeuta">Observações do Terapeuta:</label>
            <textarea class="form-control" id="observacoes_terapeuta" name="observacoes_terapeuta"></textarea>
        </div>


        <button type="submit" class="btn btn-custom">Enviar</button>
        <button type="button" class="btn btn-custom" onclick="downloadAsPDF()">Baixar PDF</button>
        <button type="button" class="btn btn-custom" onclick="downloadAsWord()">Baixar Word</button>
    </form>
</div>
<div class="overlay" id="overlay"></div>
<div class="loading-spinner" id="loadingSpinner">
    <div class="spinner-border text-primary" role="status">
        <span class="sr-only">Loading...</span>
    </div>
</div>

{% endblock %}

{% block scripts %}
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script>
    var moodData = {{ mood_data| safe }};
    var moods = ["feliz", "triste", "irritado", "ansioso", "entusiasmado", "cansado", "estressado", "indiferente", "esperancoso", "inspirado"];
    var dataValues = moods.map(mood => moodData[mood] || 0);
</script>
<script>
    function downloadAsPDF() {
        document.getElementById('form-acompanhamento').action = "{% url 'download_pdf_view_criar' %}";
        document.getElementById('form-acompanhamento').submit();
    }

    function downloadAsWord() {
        document.getElementById('form-acompanhamento').action = "{% url 'download_word' %}";
        document.getElementById('form-acompanhamento').submit();
    }
</script>
<script>
    document.addEventListener('DOMContentLoaded', function () {
        gerarRelatorioCompleto();
    });

    async function gerarRelatorioCompleto() {
        const spinner = document.getElementById('loadingSpinner');
        const overlay = document.getElementById('overlay');

        overlay.style.display = 'block';
        spinner.style.display = 'block';

        try {
            await analisarMudancaHumor();
            await new Promise(resolve => setTimeout(resolve, 2000));
            await analisarSentimento();
            await new Promise(resolve => setTimeout(resolve, 2000));
            await consultarIAeEventos();
            await new Promise(resolve => setTimeout(resolve, 2000));
        } catch (error) {
            console.error('Erro ao gerar relatório completo:', error);
            alert('Erro ao gerar relatório completo. Verifique o console para mais detalhes.');
        } finally {
            spinner.style.display = 'none';
            overlay.style.display = 'none';
        }
    }


    function formatarTextoIA(texto) {
        let textoLimpo = texto.replace(/[\\*]+/g, '');
        textoLimpo = textoLimpo.trim();
        textoLimpo = textoLimpo.replace(/\n{2,}/g, '</p><p>');
        textoLimpo = `<p>${textoLimpo}</p>`;
        textoLimpo = textoLimpo.replace(/\n/g, '<br>');
        return textoLimpo;
    }

    function analisarSentimento() {
        const csrfToken = document.querySelector('[name=csrfmiddlewaretoken]').value;
        const avaliacaoHumor = document.querySelector('#id_avaliacao_humor').value;
        return fetch("{% url 'analyze_sentiment' %}", {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'X-CSRFToken': csrfToken
            },
            body: JSON.stringify({ avaliacao_humor: avaliacaoHumor })
        })
            .then(response => response.json())
            .then(data => {
                document.getElementById('avaliacao-humor').innerHTML = formatarTextoIA(data.result);
                document.getElementById('id_avaliacao_humor').value = data.result;
            });
    }

    function analisarMudancaHumor() {
        const url = "{% url 'analyze_mood_change' %}";
        return fetch(url, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'X-CSRFToken': '{{ csrf_token }}'
            },
        })
            .then(response => response.json())
            .then(data => {
                if (data.mudancas_humor) {
                    document.getElementById('mudancas-humor').innerHTML = formatarTextoIA(data.mudancas_humor);
                    document.getElementById('id_mudancas_humor').value = data.mudancas_humor;
                } else {
                    alert('Erro ao analisar mudança de humor: ' + data.error);
                }
            });
    }

    function consultarIAeEventos() {
        const csrfToken = document.querySelector('[name=csrfmiddlewaretoken]').value;
        return fetch("{% url 'consultar_eventos' %}", {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'X-CSRFToken': csrfToken
            },
            body: JSON.stringify({ moods: moodData })
        })
            .then(response => response.json())
            .then(data => {
                if (data.success) {
                    document.getElementById('eventos-semana').innerHTML = formatarTextoIA(data.analise_ia);
                    document.getElementById('id_eventos_semana').value = data.analise_ia;
                } else {
                    alert('Erro ao buscar eventos: ' + data.error);
                }
            });
    }






    var ctx = document.getElementById('moodChart').getContext('2d');
    var moodChart = new Chart(ctx, {
        type: 'bar',
        data: {
            labels: ["Feliz", "Triste", "Irritado", "Ansioso", "Entusiasmado", "Cansado", "Estressado", "Indiferente", "Esperançoso", "Inspirado"],
            datasets: [{
                label: 'Mood da semana',
                data: dataValues,
                backgroundColor: [
                    'rgba(255, 99, 132, 0.2)',
                    'rgba(54, 162, 235, 0.2)',
                    'rgba(255, 206, 86, 0.2)',
                    'rgba(75, 192, 192, 0.2)',
                    'rgba(153, 102, 255, 0.2)',
                    'rgba(255, 159, 64, 0.2)',
                    'rgba(199, 199, 199, 0.2)',
                    'rgba(83, 102, 255, 0.2)',
                    'rgba(40, 159, 64, 0.2)',
                    'rgba(255, 99, 255, 0.2)'
                ],
                borderColor: [
                    'rgba(255, 99, 132, 1)',
                    'rgba(54, 162, 235, 1)',
                    'rgba(255, 206, 86, 1)',
                    'rgba(75, 192, 192, 1)',
                    'rgba(153, 102, 255, 1)',
                    'rgba(255, 159, 64, 1)',
                    'rgba(199, 199, 199, 1)',
                    'rgba(83, 102, 255, 1)',
                    'rgba(40, 159, 64, 1)',
                    'rgba(255, 99, 255, 1)'
                ],
                borderWidth: 1
            }]
        },
        options: {
            scales: {
                y: {
                    beginAtZero: true
                }
            }
        }
    });

</script>
{% endblock %}